@url=http://localhost:3000

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "pepito@gmail.com",
    "contraseña": "Hola1234"
}

###
@token = {{login.response.body.token}}

### Listar todos los vehiculos
GET {{url}}/vehiculos
Authorization: Bearer {{token}}

### Obtener vehiculo por id
GET {{url}}/vehiculos/1
Authorization: Bearer {{token}}

### Crear nuevo vehiculo
POST {{url}}/vehiculos
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "marca": "fiat",
    "modelo": "cronos",
    "patente": "AAT573",
    "año": 2025,
    "capacidad_carga": 1500
}

### Actualizar vehiculo
PUT {{url}}/vehiculos/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "marca": "Citroen",
    "modelo": "C4",
    "año": 2009,
    "capacidad_carga": 1600
}

### Eliminar vehiculo
DELETE {{url}}/vehiculos/1
Authorization: Bearer {{token}}